version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: FE/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=CongNgheMangNangCao
  backend:
    build:
      context: .
      dockerfile: BE/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
    - db
    environment:
      - ASPNETCORE_ENVIRONMENT=CongNgheMangNangCao
  db:
    build:
      context: .
      dockerfile: DATABASE/Dockerfile
    ports:
      - "1433:1433"