version: '3'
services:
  frontend:
    image: hoangnhii211203/linku-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=CongNgheMangNangCao
  backend:
    image: hoangnhii211203/linku-backend:latest
    ports:
      - "8081:8080"
    depends_on:
    - db
    environment:
      - ASPNETCORE_ENVIRONMENT=CongNgheMangNangCao
  db:
    image: hoangnhii211203/linku-db:latest
    ports:
      - "1433:1433"