version: '3'
services:
  frontend:
    build:
        context: .
        dockerfile: FE/Dockerfile
    image: hoangnhii211203/linku-frontend:latest
    ports:
      - "80:8080"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
  backend:
    build:
      context: .
      dockerfile: BE/Dockerfile
    image: hoangnhii211203/linku-backend:latest
    ports:
      - "7181:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release